Add html elements for mobile navigation
misikira/My-Portofilo-Website pull request #27
Opened 2023-04-18 09:39 UTC by misikira

2023-04-18 15:12 UTC, osamaashraf6 requested changes
Hi @misikira 😊, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![SoCloseAlmostGIF (2)](https://user-images.githubusercontent.com/83360636/232804023-e2b0e10b-90e5-4b02-bf56-4fc1bd7350c1.gif)

## Highlights 🚀🎉🎉
- [x] Not linter errors present
- [x] Good descriptive pull request👌💯
- [x] Nice design for the project 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 10:31 UTC, IngDavidTM requested changes
## Hi @misikira  🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

- [OPTIONAL] Kindly consider remove horizontal scroll that makes the page not like the Figma Design, so let's try to fix this scroll to make your page like the Figma Design also to make it better for the users who will see your portfolio and communicate with you :+1:.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 10:31 UTC, IngDavidTM commented on index.html
> +                        <a href="#" class="menu-option" id="closeMenuNavigation"><li>X</li></a>
- [ ] While you make progress with the design :+1:, as requested by the previous reviewer try to add the `X` icon at the correct position because right now it is not showing in your mobile menu.
- [ ] Also, as mentioned by the previous reviewer, consider making it blur as the Figma to not make the text on the Home page disappears from the links in the mobile navigation :+1:.


**Your design**

![Screenshot from 2023-04-19 05-21-58](https://user-images.githubusercontent.com/105117832/233046802-03912f50-bff4-49d6-aab7-a816738d6b2e.png)

**Figma**

![Screenshot from 2023-04-19 05-29-01](https://user-images.githubusercontent.com/105117832/233047755-69ae593b-f7cb-4c82-b12b-a87597c571c6.png)

2023-04-19 11:54 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/YPI7uEvEZr7siYRlZD/giphy.gif)

# Hi @misikira  👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- Check the comments below...

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-19 11:54 UTC, AbelG101 commented on style.css
> +}
- [ ] [OPTIONAL] I noticed the background blur effect is not yet implemented so I'd advise you to do some research on adding a blur to a background in CSS. As a front-end developer, you should make a habit of researching things you don't know how to implement and trying them out. 💪
- [ ] Here's [an article](https://blog.prototypr.io/how-to-make-a-background-blur-in-css-with-one-line-of-code-e446c7236e60) that can help you. Good luck!

2023-04-19 11:59 UTC, merged